export const FORGET_PASS_STEPS = {
  SEND_EMAIL: "SEND_EMAIL",
  VERIFY_CODE: "VERIFY_CODE",
  NEW_PASSWORD: "NEW_PASSWORD",
} as const;

export const LOCAL_STORAGE_KEYS = {
  CURRENT_EMAIL: "CURRENT_EMAIL",
  RESEND_DATE: "RESEND_DATE",
} as const;
